- ControlMode: "ACC"
- YawUse: false
- U: 0.5
- U_YAW: 0
- SampleNum: 1
- Dt: 1.0
- MAX_VEL: 1.0
- MAX_ACC: 1.0
- MAX_JRK: 1.0
- MAX_YAW: 1.0
- TOL_POS: 0.5
- TOL_VEL: -1.0
- TOL_ACC: -1.0
- TOL_YAW: -1.0
- WJ: 1
- WT: 10
- WYaw: 0
- Map_Type: 1
- Heur_Type: 0
- MP_PENALTY: 0
- YAWMP_PENALTY: 0